# Generated by Django 6.0.6 on 2026-06-13 14:38

import django.db.models.deletion
import myapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_academictask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(default='Untitled Analysis', help_text='The AI-generated main topic heading for the card UI.', max_length=255)),
                ('ai_summary', models.TextField(blank=True, help_text='The core Markdown/Text summary rendered inside the .note_main container.', null=True)),
                ('file_name', models.CharField(help_text="The original name displayed in the card footer (e.g., 'cryptography_notes.pdf' or 'Raw Text Analysis').", max_length=255)),
                ('uploaded_file', models.FileField(blank=True, help_text='Stores the physical file if uploaded. Blank if text was pasted.', null=True, upload_to=myapp.models.user_notes_directory_path, validators=[myapp.models.validate_note_file_extension])),
                ('raw_extracted_text', models.TextField(blank=True, help_text='Stores the plain text extracted from files or pasted directly. Used as the context source for LLM operations.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Academic Note',
                'verbose_name_plural': 'Academic Notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
