# Generated by Django 6.0.6 on 2026-06-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_academicnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicnote',
            name='tags',
            field=models.JSONField(default=list, help_text='List of AI-generated tags for the UI.'),
        ),
    ]
